name: aoc2023
version: 0.1.0

ghc-options: -Wall
default-extensions:
  - ApplicativeDo
language: GHC2021

library:
  source-dirs: src
  dependencies:
    - base
    - errors
    - containers

executables:
  aoc2023:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc2023
      - errors
      - base
    data-files:
      - input/*.txt

tests:
  spec:
    main: Spec.hs
    build-tools: hspec-discover:hspec-discover
    source-dirs: test
    dependencies:
      - aoc2023
      - base
      - hspec
