name: aoc2023
version: 0.1.0

ghc-options: -Wall
default-extensions:
  - NoImplicitPrelude
  - OverloadedRecordDot
  - OverloadedLists
language: GHC2021

data-files:
  - input/*.txt

library:
  source-dirs: src
  dependencies:
    - base
    - errors
    - containers
    - vector

executables:
  aoc2023:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc2023
      - errors
      - base

tests:
  spec:
    main: Spec.hs
    build-tools: hspec-discover:hspec-discover
    source-dirs: test
    dependencies:
      - aoc2023
      - base
      - hspec
